<?php
/**
 * SilverTouch Technologies Limited.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 *
 * @category   Sttl
 * @package    Sttl_Topcart
 * @copyright  Copyright (c) 2011 SilverTouch Technologies Limited. (http://www.silvertouch.com/MagentoExtensions)
 * @license    http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 */ 
 ?>
<?php $_cartQty = $this->getSummaryCount() ?>
<?php if ($_cartQty > 0): ?>
    <?php $_myCart = $this->__('My Cart (<span>%s</span>)', $_cartQty) ?>
<?php else: ?>
    <?php $_myCart = $this->__('My Cart (<span>0</span>)') ?>
<?php endif ?>
<div class="dhtmlgoodies_question"><?php echo $_myCart ?></div>
<div class="dhtmlgoodies_answer">
	<div>
		<div class="inner-wrapper"><?php // extra div to smooth slideUp and slideDown ?>
        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)): ?>
            <p class="block-subtitle">
                <?php echo $this->__('Recently added item(s)') ?>
            </p>
            <ol id="mini-cart" class="mini-products-list">
            <?php foreach($_items as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('mini-cart', 'none-recursive')</script>
        <?php else: ?>
            <p class="block-subtitle">              
                <?php echo $this->__('Recently added item(s)') ?>
            </p>
            <p class="cart-empty">
                <?php echo $this->__('You have no items in your shopping cart.') ?>
            </p>
        <?php endif ?>
        <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
            <p class="subtotal">
                <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?><?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?> / <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?><?php endif; ?>
            </p>
            <div class="actions">
                <?php echo $this->getChildHtml('extra_actions') ?>
                <button class="button" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('Go to Shopping Cart') ?></span></a>
            </div>
        <?php endif ?>
        </div>
	</div>
</div>

<!-- extra content -->

<script type="text/javascript">
window.onload = initShowHideDivs;
</script>
